"""Independent receipt fixtures, never generated by the collector under test.

Only the expensive pinned-base reader is mocked in unit fixtures. Real source
codec/load, verifier code hashes, request checks and immutable handles remain
active. Optional integration uses the real pinned ZIP with an absent token.
"""
from __future__ import annotations

from collections import Counter
import copy
from dataclasses import FrozenInstanceError
from datetime import date, timedelta
import hashlib
import io
import json
import os
from pathlib import Path
import socket
from types import SimpleNamespace
import urllib.request  # Initialize ssl types before replacing socket in offline fixtures.
import zipfile

import pytest

from work.profit_1000_upgrade import candidate_scope_verify as v

RUN_ID, COMMIT = "123456789", "a" * 40


def encode(value):
    return (json.dumps(value, sort_keys=True, ensure_ascii=False, indent=2, allow_nan=False) + "\n").encode()


def forbidden(*args, **kwargs):
    raise AssertionError("no HTTP, collector, training, labels or writes during verification")


def fixture_scope(base_bytes, members):
    dates = {(date(2025, 1, 1) + timedelta(days=n)).strftime("%Y%m%d") for n in range(210)}
    dates.update(v.inputs.PREFLIGHT_T_DATES)
    dates = sorted(dates)
    assert len(dates) == 212
    codes = {day: [f"{600000 + j:06d}.SH" for j in range(8 if i < 48 else 9)] for i, day in enumerate(dates)}
    for day, code in v.PREFLIGHT: codes[day][0] = code
    return {"base_archive": {"sha256": hashlib.sha256(base_bytes).hexdigest(), "bytes": len(base_bytes), "synthetic_fixture": True},
        "frozen_manifest": {"rows": [], "synthetic_fixture": True}, "gap_dates": dates,
        "gap_candidate_codes": codes, "reused_dates": ["20250116"], "precoverage_dates": ["20241231"],
        "code_bindings": [{"path": name, "sha256": v.inputs._file_sha(v.CHECKOUT / name)} for name in sorted(v.inputs.CODE_PATHS)],
        "archive_file_bindings": [{"path": name, "sha256": hashlib.sha256(raw).hexdigest(), "bytes": len(raw)} for name, raw in members.items()]}


def binding(root, path):
    raw = path.read_bytes()
    return {"path": path.relative_to(root).as_posix(), "sha256": hashlib.sha256(raw).hexdigest(), "bytes": len(raw)}


def blank(day, code, status="NOT_REQUESTED_BUDGET_EXHAUSTED"):
    return {"trade_date": day, "ts_code": code, "request": v.source.request_contract(day, code),
        "preflight": (day, code) in v.PREFLIGHT, "api_calls": 0, "request_sequence": None,
        "status": status, "reason": None, "network_request_performed": False,
        "http_response_sha256": None, "http_response_bytes": None, "source_files": [], "rows": None}


def success(root, item, sequence, *, empty=False):
    day, code = item["trade_date"], item["ts_code"]
    raw = encode({"code": 0, "detail": "...", "data": {"fields": list(v.source.FIELDS),
        "items": [] if empty else [[code, day, "7.65999", 100, None, 7.1]], "has_more": False, "count": 0}})
    bodies = v.source.source_bytes(raw, day, code, request=item["request"], fetched_at_utc="2026-09-13T01:00:00Z", network_request_performed=True)
    paths = v.source.source_paths(root, day, code)
    for path, body in zip(paths, bodies):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(body)
    item.update(api_calls=1, request_sequence=sequence, network_request_performed=True,
                http_response_sha256=hashlib.sha256(raw).hexdigest(), http_response_bytes=len(raw),
                status="CANDIDATE_TABLE_EMPTY" if empty else "CANDIDATE_TABLE_PRESENT", rows=0 if empty else 1,
                source_files=[binding(root, path) for path in paths])


def refresh(root, report, *, counts=True):
    rows = report["requests"]
    journal = sorted((r for r in rows if r["api_calls"]), key=lambda r: r["request_sequence"])
    (root / v.JOURNAL).write_bytes(b"".join(json.dumps(row, sort_keys=True).encode() + b"\n" for row in journal))
    report["source_files"] = sorted((b for r in rows for b in r["source_files"]), key=lambda b: b["path"])
    report["output_file_bindings"] = sorted((binding(root, path) for path in root.rglob("*") if path.is_file() and path.name != v.RECEIPT), key=lambda b: b["path"])
    if counts:
        report.update(api_calls=sum(r["api_calls"] for r in rows), qualified_new_source_pairs=sum(r["status"] in v.source.STATUSES for r in rows),
                      new_source_status_counts=dict(Counter(r["status"] for r in rows)))
    (root / v.RECEIPT).write_bytes(encode(report))


def verify(root, **overrides):
    return v.verify(root, **{"expected_run_id": RUN_ID, "expected_run_commit": COMMIT, **overrides})


@pytest.fixture
def artifact(tmp_path, monkeypatch):
    root = tmp_path / "collection"
    root.mkdir()
    members = {v.inputs.LABELS: encode({"as_of_date": "20260911", "rows": ["old outcomes must never be consumed"]}),
               "old/original.bin": b"\x00\xff preserve all members"}
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w") as archive:
        for name, raw in members.items(): archive.writestr(name, raw)
    base_bytes = buffer.getvalue()
    (root / v.BASE).write_bytes(base_bytes)
    scope = fixture_scope(base_bytes, members)
    def read_base(path):
        assert Path(path) == root / v.BASE
        if Path(path).read_bytes() != base_bytes: raise ValueError("PINNED_BASE_ARCHIVE_CHANGED")
        return copy.deepcopy(scope)
    monkeypatch.setattr(v.inputs, "read_base_archive", read_base)
    monkeypatch.setattr(socket, "socket", forbidden)
    rows = [blank(day, code) for day in scope["gap_dates"] for code in scope["gap_candidate_codes"][day]]
    rows.sort(key=lambda r: (r["trade_date"], r["ts_code"]))
    assert len(rows) == 1860
    by_pair = {(r["trade_date"], r["ts_code"]): r for r in rows}
    for sequence, pair in enumerate(v.PREFLIGHT, 1): success(root, by_pair[pair], sequence)
    # Gap document deliberately follows collector's pretty JSON checksum,
    # whereas authority.frozen_manifest_sha256 uses compact historic checksum.
    manifest = {"schema_version": "dc20_candidate_auction_gap_manifest_v1", "base_archive": scope["base_archive"],
        "scope_counts": dict(v.inputs.COUNTS), "gap_dates": scope["gap_dates"], "gap_candidate_codes": scope["gap_candidate_codes"],
        "reused_dates": scope["reused_dates"], "precoverage_dates": scope["precoverage_dates"],
        "preflight_pairs": [list(p) for p in v.PREFLIGHT], "frozen_manifest_sha256": hashlib.sha256(encode(scope["frozen_manifest"])).hexdigest(),
        "old_outcomes_used_for_scope": False}
    (root / v.MANIFEST).write_bytes(encode(manifest))
    report = {"schema_version": v.SCHEMA, "status": "SOURCE_PAIRS_PARTIAL", "base_archive": scope["base_archive"],
        "source_policy_id": v.source.SOURCE_POLICY_ID, "scope_counts": dict(v.inputs.COUNTS),
        "preflight_pairs": [list(p) for p in v.PREFLIGHT], "preflight_passed": True,
        "eligible_as_real_collection": True, "callable_injected_for_test": False, "max_api_calls": 1860, "retries": 0,
        "elapsed_collection_seconds": 2980.1, "reused_base_source_dates": len(scope["reused_dates"]),
        "requests": rows, "execution_file_bindings": {name: v.inputs._file_sha(v.CHECKOUT / name) for name in v.inputs.CODE_PATHS | v.NEW_CODE},
        "observed_at_utc": "2026-09-13T01:01:00Z", "run_id": RUN_ID, "run_commit": COMMIT, **v.FLAGS}
    refresh(root, report)
    return root, report, scope


def test_independent_partial_replay_returns_private_immutable_authority(artifact, monkeypatch):
    root, report, scope = artifact
    from work.profit_1000_upgrade import candidate_scope_collect
    monkeypatch.setattr(candidate_scope_collect, "run_collection", forbidden)
    monkeypatch.setattr(candidate_scope_collect, "expected_contract", forbidden)
    for name in ("source_bytes",): monkeypatch.setattr(v.source, name, forbidden)
    monkeypatch.setattr(Path, "write_bytes", forbidden)
    monkeypatch.setattr(Path, "write_text", forbidden)
    value = verify(root)
    assert type(value) is v.VerifiedCandidateCollection
    assert value.root == root and value.source_only and not value.label_source_eligible
    assert value.gap_pairs == tuple(sorted((r["trade_date"], r["ts_code"]) for r in report["requests"]))
    assert value.successful_pairs == tuple(sorted(v.PREFLIGHT)) and len(value.source_bindings) == 4
    assert value.as_of_date == "20260911" and value.frozen_manifest_sha256 == v.inputs._manifest_sha(scope["frozen_manifest"])
    assert value.receipt_sha256 == hashlib.sha256((root / v.RECEIPT).read_bytes()).hexdigest()
    assert value.base_archive_sha256 == scope["base_archive"]["sha256"]
    assert len(value.base_file_bindings) == 2 and all("path" in b and "sha256" in b for b in value.base_file_bindings)
    assert value.assert_unchanged() is None
    assert v.reload_verified(value).receipt_sha256 == value.receipt_sha256
    with pytest.raises(FrozenInstanceError): value.source_only = False
    with pytest.raises(TypeError): value.source_bindings[0]["sha256"] = "0" * 64
    with pytest.raises(TypeError): value.scope["gap_candidate_codes"]["20250319"] = ()
    assert not hasattr(value, "__dict__")


@pytest.mark.parametrize("value", [True, {}, {"source_only": True}, SimpleNamespace(source_only=True)])
def test_dictionary_boolean_and_duck_type_cannot_supply_authority(value):
    with pytest.raises(ValueError, match="EXACT_VERIFIED_COLLECTION_REQUIRED"): v.reload_verified(value)
    with pytest.raises(ValueError, match="PRIVATE_CONSTRUCTION"): v.VerifiedCandidateCollection(root=Path("/tmp"))


@pytest.mark.parametrize("key,value", [("callable_injected_for_test", True), ("eligible_as_real_collection", False),
    ("source_only", False), ("source_only", 1), ("label_rebuild_performed", True), ("production_writes", True),
    ("source_policy_id", "v3"), ("max_api_calls", 1861), ("retries", 1), ("schema_version", "old"),
    ("qualified_new_source_pairs", 3), ("reused_base_source_dates", 2), ("status", "SOURCE_PAIRS_COLLECTED"),
    ("preflight_passed", False), ("run_id", "bad"), ("run_commit", "bad"), ("elapsed_collection_seconds", True),
    ("elapsed_collection_seconds", 1), ("observed_at_utc", "2026-09-13T09:00:00+08:00")])
def test_receipt_authority_counts_identity_and_timing_tamper(artifact, key, value):
    root, report, _ = artifact
    report[key] = value
    refresh(root, report, counts=False)
    with pytest.raises(ValueError): verify(root)


@pytest.mark.parametrize("id,commit", [(None, None), (RUN_ID, None), (None, COMMIT), ("9999", COMMIT), (RUN_ID, "b" * 40)])
def test_requested_artifact_needs_matching_external_identity(artifact, id, commit):
    root, _, _ = artifact
    with pytest.raises(ValueError, match="EXTERNAL_RUN_IDENTITY"):
        v.verify(root, expected_run_id=id, expected_run_commit=commit)


@pytest.mark.parametrize("kind", ["missing", "duplicate", "reorder", "code", "extra_key", "preflight_bool", "network_bool", "calls_bool", "status", "reason"])
def test_all_1860_requests_and_exact_fields_required(artifact, kind):
    root, report, _ = artifact
    rows = report["requests"]
    if kind == "missing": rows.pop()
    elif kind == "duplicate": rows[-1] = copy.deepcopy(rows[0])
    elif kind == "reorder": rows.reverse()
    elif kind == "code": rows[0]["ts_code"] = "600999.SH"
    elif kind == "extra_key": rows[0]["injected"] = True
    elif kind == "preflight_bool": rows[0]["preflight"] = 0
    elif kind == "network_bool": rows[0]["network_request_performed"] = 0
    elif kind == "calls_bool": rows[0]["api_calls"] = False
    elif kind == "status": rows[0]["status"] = "NO_FILL_SOURCE_ERROR"
    else: rows[0]["reason"] = "MADE_UP"
    refresh(root, report)
    with pytest.raises(ValueError): verify(root)


@pytest.mark.parametrize("kind", ["STK", "offset", "wrongstock", "fullmarket", "fields", "future"])
def test_request_scope_cannot_be_rewritten(artifact, kind):
    root, report, _ = artifact
    row = report["requests"][0]
    if kind in ("STK", "offset"): row["request"]["params"]["ts_type" if kind == "STK" else "offset"] = "STK"
    elif kind == "wrongstock": row["request"]["params"]["ts_code"] = "600999.SH"
    elif kind == "fullmarket": del row["request"]["params"]["ts_code"]
    elif kind == "future": row["request"]["params"]["trade_date"] = "20260914"
    else: row["request"]["fields"].reverse()
    refresh(root, report)
    with pytest.raises(ValueError): verify(root)


@pytest.mark.parametrize("kind", ["rowcount", "http_sha", "http_bytes", "success_reason", "source_order", "sequence_duplicate", "sequence_swap"])
def test_success_requires_replayed_source_http_meta_and_request_sequence(artifact, kind):
    root, report, _ = artifact
    present = [r for r in report["requests"] if r["api_calls"]]
    row = present[0]
    if kind == "rowcount": row["rows"] = 0
    elif kind == "http_sha": row["http_response_sha256"] = "1" * 64
    elif kind == "http_bytes": row["http_response_bytes"] += 1
    elif kind == "success_reason": row["reason"] = "ERROR"
    elif kind == "source_order": row["source_files"].reverse()
    elif kind == "sequence_duplicate": present[1]["request_sequence"] = row["request_sequence"]
    else: present[0]["request_sequence"], present[1]["request_sequence"] = present[1]["request_sequence"], present[0]["request_sequence"]
    refresh(root, report)
    with pytest.raises(ValueError): verify(root)


def test_complete_empty_regular_pair_is_source_not_price_authority(artifact):
    root, report, _ = artifact
    row = next(r for r in report["requests"] if not r["preflight"])
    success(root, row, 3, empty=True)
    refresh(root, report)
    value = verify(root)
    assert (row["trade_date"], row["ts_code"]) in value.successful_pairs
    assert not value.label_source_eligible and value.status == "SOURCE_PAIRS_PARTIAL"


@pytest.mark.parametrize("failed_index", [0, 1])
@pytest.mark.parametrize("kind", ["empty", "network", "http", "invalid"])
def test_preflight_failure_stops_all_later_pairs(artifact, failed_index, kind):
    root, report, _ = artifact
    rows = report["requests"]
    selected = {(r["trade_date"], r["ts_code"]): r for r in rows}
    for row in rows:
        pair = row["trade_date"], row["ts_code"]
        if pair in set(v.PREFLIGHT[:failed_index]): continue
        for item in row["source_files"]:
            (root / item["path"]).unlink()
        # Remove fixture directories left by deliberately undoing preflight.
        directory = v.source.source_paths(root, *pair)[0].parent
        while directory != root and directory.exists() and not any(directory.iterdir()):
            parent = directory.parent; directory.rmdir(); directory = parent
        row.clear(); row.update(blank(*pair, status="NOT_REQUESTED_PREFLIGHT_BLOCKED"))
    failed = selected[v.PREFLIGHT[failed_index]]
    if kind == "empty": success(root, failed, failed_index + 1, empty=True)
    else:
        failed.update(api_calls=1, request_sequence=failed_index + 1, network_request_performed=True,
                      status={"network": "PENDING_NETWORK_OR_RESPONSE_ERROR", "http": "PENDING_HTTP_ERROR", "invalid": "PENDING_INVALID_CANDIDATE_SOURCE"}[kind])
        if kind == "http": failed["reason"] = "HTTP_429"
        if kind == "invalid": failed.update(reason="CANDIDATE_TABLE_REQUIRES_EXPLICIT_COMPLETENESS", http_response_sha256="c" * 64, http_response_bytes=100)
    report.update(status="PREFLIGHT_BLOCKED", preflight_passed=False)
    refresh(root, report)
    assert verify(root).status == "PREFLIGHT_BLOCKED"
    later = next(r for r in rows if not r["preflight"])
    later.update(status="PENDING_NETWORK_OR_RESPONSE_ERROR", api_calls=1, request_sequence=failed_index + 2, network_request_performed=True)
    refresh(root, report)
    with pytest.raises(ValueError, match="AFTER_PREFLIGHT_FAILURE"): verify(root)


@pytest.mark.parametrize("pathkind", ["source", "metadata", "receipt", "base", "journal", "new_file", "emptydir"])
def test_authority_recheck_catches_every_output_change(artifact, pathkind):
    root, report, _ = artifact
    value = verify(root)
    if pathkind == "source": path = root / report["source_files"][0]["path"]
    elif pathkind == "metadata": path = root / next(b["path"] for b in report["source_files"] if b["path"].endswith("meta.json"))
    elif pathkind == "receipt": path = root / v.RECEIPT
    elif pathkind == "base": path = root / v.BASE
    elif pathkind == "journal": path = root / v.JOURNAL
    elif pathkind == "new_file": path = root / "unregistered.json"
    else:
        (root / "empty").mkdir()
        with pytest.raises(ValueError): value.assert_unchanged()
        return
    path.write_bytes(b"changed")
    with pytest.raises(ValueError): value.assert_unchanged()
    with pytest.raises(ValueError): v.reload_verified(value)


@pytest.mark.parametrize("kind", ["extra", "missing", "sha", "baseprovenance", "manifest", "journal"])
def test_binding_set_and_scope_documents_cannot_change(artifact, kind):
    root, report, _ = artifact
    if kind == "extra": (root / "extra.json").write_bytes(b"{}")
    elif kind == "missing": (root / report["source_files"][0]["path"]).unlink()
    elif kind == "sha": report["source_files"][0]["sha256"] = "0" * 64
    elif kind == "baseprovenance": report["base_archive"]["sha256"] = "0" * 64
    elif kind == "manifest": (root / v.MANIFEST).write_bytes(b"{}")
    else:
        (root / v.JOURNAL).write_bytes(b"{}\n")
        report["output_file_bindings"] = [binding(root, root / b["path"]) for b in report["output_file_bindings"]]
        (root / v.RECEIPT).write_bytes(encode(report))
        with pytest.raises(ValueError): verify(root)
        return
    refresh(root, report)
    with pytest.raises(ValueError): verify(root)


@pytest.mark.parametrize("kind", ["hardlink", "symlink", "case", "traversal"])
def test_nonregular_alias_or_unsafe_bound_paths_rejected(artifact, kind):
    root, report, _ = artifact
    if kind == "hardlink": os.link(root / v.BASE, root / "alias.zip")
    elif kind == "symlink": (root / "alias.zip").symlink_to(root / v.BASE)
    elif kind == "case": (root / v.BASE.upper()).write_bytes(b"bad")
    else:
        report["source_files"][0]["path"] = "../escape"
        (root / v.RECEIPT).write_bytes(encode(report))
    with pytest.raises(ValueError): verify(root)


def test_code_and_contract_snapshots_revalidated(artifact, monkeypatch):
    root, _, _ = artifact
    value = verify(root)
    original = v.inputs._file_sha
    target = v.CHECKOUT / "work/profit_1000_upgrade/candidate_scope_collect.py"
    monkeypatch.setattr(v.inputs, "_file_sha", lambda path: "0" * 64 if Path(path) == target else original(path))
    with pytest.raises(ValueError, match="VERIFIED_CODE_CHANGED"): value.assert_unchanged()
    with pytest.raises(ValueError, match="EXECUTION_CODE_SHA"): verify(root)


def test_observed_time_cannot_precede_source_fetch(artifact):
    root, report, _ = artifact
    report["observed_at_utc"] = "2026-09-13T00:59:59Z"
    refresh(root, report)
    with pytest.raises(ValueError, match="FETCH_AFTER_RECEIPT"): verify(root)


def test_guarded_asof_comes_from_bound_old_metadata_only(artifact, monkeypatch):
    root, _, scope = artifact
    copied = copy.deepcopy(scope)
    copied["archive_file_bindings"][0]["sha256"] = "0" * 64
    monkeypatch.setattr(v.inputs, "read_base_archive", lambda _: copied)
    with pytest.raises(ValueError, match="BASE_LABEL_METADATA_BINDING"): verify(root)


def test_full_1860_source_pairs_replay_without_filtering_empty_or_numeric_errors(artifact):
    root, report, _ = artifact
    sequence = 2
    for row in report["requests"]:
        if row["preflight"]: continue
        sequence += 1
        success(root, row, sequence, empty=sequence % 2 == 0)
    report["status"] = "SOURCE_PAIRS_COLLECTED"
    refresh(root, report)
    value = verify(root)
    assert value.status == "SOURCE_PAIRS_COLLECTED" and len(value.successful_pairs) == 1860
    assert len(value.source_bindings) == 3720 and len(value._output_bindings) == 3724


@pytest.mark.skipif(not os.environ.get("DC20_CANDIDATE_REAL_BASE"), reason="explicit real pinned ZIP integration opt-in")
def test_real_base_zero_call_blocked_end_to_end(tmp_path, monkeypatch):
    from work.profit_1000_upgrade import candidate_scope_collect as collector
    monkeypatch.setenv("GITHUB_RUN_ATTEMPT", "1")
    monkeypatch.setenv("GITHUB_RUN_ID", RUN_ID)
    monkeypatch.setenv("GITHUB_SHA", COMMIT)
    monkeypatch.setattr(collector, "official_call", forbidden)
    output = tmp_path / "real-base-zero-call"
    result = collector.run_collection(Path(os.environ["DC20_CANDIDATE_REAL_BASE"]), output, token="")
    assert result["api_calls"] == 0 and result["status"] == "PREFLIGHT_BLOCKED"
    value = verify(output)
    assert value.base_archive_sha256 == v.inputs.BASE_SHA256 and len(value.gap_pairs) == 1860
    assert value.successful_pairs == () and len(value.base_file_bindings) == 7676 and value.as_of_date == "20260911"
    value.assert_unchanged()
