'use strict';
let S=null;const $=x=>document.getElementById(x);const esc=x=>String(x??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const pc=x=>x==null?'—':(x*100).toFixed(1)+'%';const fee=x=>x==null?'—':(x*100).toFixed(2)+'%';const dt=x=>x?new Date(x).toLocaleString('zh-CN',{hour12:false}):'未记录';const empty=x=>`<div class="empty">${esc(x)}</div>`;const kpi=(a,b,c)=>`<div class="kpi"><small>${esc(a)}</small><strong>${esc(b)}</strong><em>${esc(c)}</em></div>`;const prov=x=>({PROSPECTIVE_LOCAL:'事前本地冻结',LEGACY_UNVERIFIED_FREEZE:'历史导入 · 冻结待审计',RETROSPECTIVE:'事后补算 · 不计预测验证'}[x]||x);const stat=x=>({SETTLED:'已结算',UNFILLED:'未买入',UNEXITED:'未退出',MISSING:'缺结果数据',OUT_OF_SCENARIO:'超出入场情景',CONFLICT:'结果冲突待审'}[x]||x);
const rated=r=>r.p!=null&&r.payload.independent_rank_eligible!==false&&r.payload.probability_method!=='UNINFORMED';
function displayOutcomes(r){const linked=S?.reconciliation?.rows.find(x=>x.prediction_id===r.id);if(!linked)return r.outcomes;return Object.entries(linked.outcomes).filter(([basis,o])=>o.source!=='NONE').map(([basis,o])=>({...o,basis}))}
function dayRows(){return S.predictions.filter(x=>x.signal_date===$('day').value&&x.model===$('predictionVersion').value)}
function versions(){const all=S.predictions.filter(x=>x.signal_date===$('day').value);const ms=[...new Set(all.map(x=>x.model))];$('predictionVersion').innerHTML=ms.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');if(ms.length)$('predictionVersion').value=ms[ms.length-1];}
function selectedMap(){const m=new Map();for(const r of dayRows())m.set(r.code,r);return m}
function card(x,label,m){const r=m.get(x.ts_code),p=r&&rated(r)?r.p:null;return `<div class="stockcard"><div><small>${esc(label)}</small><b>${esc(x.name||r?.name||x.ts_code)}</b><small>${esc(x.ts_code)}</small></div><div class="prob${p==null?' unrated':''}">${pc(p)}<small>独立盈利估计${p==null?' · 未评级':''}</small></div></div>`}
function render(){const day=$('day').value,rows=dayRows(),f=S.official[day],m=selectedMap();const settled=rows.filter(r=>displayOutcomes(r).some(o=>o.status==='SETTLED')).length;$('updated').textContent='页面读取 '+dt(S.generated_at);$('statusBanner').textContent='研究阶段 · 夜间维护已接入；训练仍需合格样本与成交审核。';$('kpis').innerHTML=kpi('当日候选 / 结构化预测',(f?.count??'—')+' / '+rows.length,'旧报告不会自动当作可训练样本')+kpi('合规事前预测',rows.filter(x=>x.provenance==='PROSPECTIVE_LOCAL').length,'历史导入不追认为前瞻验证')+kpi('已登记结算',settled,'实际成交与行情代理分别统计')+kpi('待补信号日',S.pending.length,'来自定时任务最后保存状态');$('profitCards').innerHTML=f?f.rows.filter(x=>x.candidate_rank<=2).map(x=>card(x,'DC20 盈'+x.candidate_rank,m)).join(''):empty('同D正式盈利冻结未核验');$('promotionCards').innerHTML=f?f.promotion.filter(x=>x.promotion_rank<=3).sort((a,b)=>a.promotion_rank-b.promotion_rank).map(x=>card(x,'晋'+x.promotion_rank,m)).join(''):empty('同D正式晋级名单未核验');const probs=rows.filter(rated),best=Math.max(...probs.map(r=>r.p));const top=probs.filter(r=>r.p===best),shared=f?.rows.filter(x=>x.candidate_rank<=2&&top.some(r=>r.code===x.ts_code))||[];$('comparison').textContent=f?`D ${day} · T ${f.exec_date} · T+1 ${f.exit_date} 10:00。官方来源为归档冻结（非当前在线核验）。独立前列与官方前二重合 ${shared.length} 只；重合不证明胜率提高。`:'正式身份缺失，暂停共振比较。';renderRows();renderContext();$('details').hidden=true;
const cov=[['完整 MA5/10/20/30/60',rows.filter(x=>x.display_evidence?.ma_complete).length,'绑定证据计算值；非原始日线完整性审核'],['可核验日线条数 ≥60',rows.filter(x=>x.display_evidence?.daily_count>=60).length,'未存条数时记未核验，不从MA60反推'],['板块1/3/5/10/20日资金窗口',rows.filter(x=>x.display_evidence?.sector_windows).length,'绑定资金证据；历史成分有效期另行审核'],['证据读取异常',rows.filter(x=>x.display_evidence?.errors.length).length,'哈希或归档异常不计覆盖'],['固定10:00已登记结果',settled,'实际与代理分别见结果表']];$('coverage').innerHTML='<table><thead><tr><th>维度</th><th>覆盖 / 预测数</th><th>状态</th></tr></thead><tbody>'+cov.map(x=>`<tr><td>${x[0]}</td><td>${x[1]} / ${rows.length}</td><td>${x[2]}</td></tr>`).join('')+'</tbody></table>';
const prev=$('model').value;$('model').innerHTML=S.models.map(x=>`<option value="${esc(x.id)}">${esc(x.id)}</option>`).join('');if(S.models.some(x=>x.id===prev))$('model').value=prev;else if(rows.length)$('model').value=rows[0].model;renderEval();$('models').innerHTML=S.models.map(x=>`<div class="flowrow"><b>${esc(x.id)}</b><span>研究归档 · ${esc(x.kind)} · 未准入生产</span></div>`).join('');$('ops').innerHTML='<div>'+[['数据库完整性',S.db_integrity],['原始归档版本',S.artifacts],['最后任务记录',dt(S.last_check)],['常规定时','交易日22:00（外部任务记录）']].map(x=>`<div class="flowrow"><b>${x[0]}</b><span>${esc(x[1])}</span></div>`).join('')+'</div><div>'+[['行情采集','公开图表批量采集已验证；非实时/Level2'],['结果回填','命令行校验导入'],['数据库备份','夜间维护入口自动备份原文及数据库，校验回读'],['自动训练 / 晋升','合格样本触发研究训练 / 自动晋升禁用']].map(x=>`<div class="flowrow"><b>${x[0]}</b><span>${x[1]}</span></div>`).join('')+'</div>';$('alerts').innerHTML=S.alerts.map(x=>`<div class="notice">${esc(x.message)}</div>`).join('');renderClosedLoop();$('audit').innerHTML=S.audit.map(x=>`<div class="audit"><b>${esc(x.event)}</b> <small>${dt(x.at)}</small><div>${esc(x.detail)}</div></div>`).join('');$('dbstatus').textContent='SQLite · 仅127.0.0.1 · 无外部页面资源';}
function renderRows(){const f=S.official[$('day').value],q=$('search').value.trim();const all=dayRows().sort((a,b)=>(rated(b)?b.p:-1)-(rated(a)?a.p:-1));$('rows').innerHTML=all.filter(r=>!q||(r.code+r.name).includes(q)).map(r=>{const rank=!rated(r)?'无信息 / 未评级':1+all.filter(x=>rated(x)&&x.p>r.p).length;const same=all.filter(x=>rated(x)&&x.p===r.p).length;const off=f?.rows.find(x=>x.ts_code===r.code),promotion=f?.promotion.find(x=>x.ts_code===r.code),tags=[];if(off?.candidate_rank<=2)tags.push('盈'+off.candidate_rank);if(promotion?.promotion_rank<=3)tags.push('晋'+promotion.promotion_rank);return `<tr><td>${esc(rank)}${rated(r)&&same>1?'（并列）':''}</td><td><b>${esc(r.name)}</b><small>${esc(r.code)}</small></td><td>${tags.join(' · ')||'—'}</td><td><b>${pc(r.p)} / ${pc(r.p==null?null:1-r.p)}</b><small>${rated(r)?'低可信度 · 未校准':'无信息占位 · 不参与排名 · 不可据此交易'}</small></td><td>${esc(prov(r.provenance))}</td><td>${displayOutcomes(r).length?displayOutcomes(r).map(o=>esc(stat(o.status))+' / '+(o.basis==='ACTUAL'?'实际':'代理')).join('<br>'):esc(({WAITING_ENTRY:'待T入场',WAITING_EXIT_FILL_UNCONFIRMED:'待T+1退出 · 成交未确认',DUE_FOR_OUTCOME_EVIDENCE:'已到期 · 待结果证据',LEGACY_REQUIRES_EVIDENCE_AUDIT:'历史证据待审计'})[r.research_stage]||'尚未登记结果')}</td><td><button data-id="${r.id}">查看</button></td></tr>`}).join('');if(!all.length)$('rows').innerHTML='<tr><td colspan="7">没有结构化预测记录；不从报告文字猜测概率。</td></tr>';}
function details(id){const r=S.predictions.find(x=>x.id===id);const m=r.display_evidence?.metrics||r.payload.metrics||{};$('details').hidden=false;$('details').innerHTML=`<div class="sectionhead"><h3>${esc(r.name)} · ${esc(r.code)} · 预测ID ${r.id}</h3><button id="closeDetail">收起</button></div><p>${esc(prov(r.provenance))}。入场情景：${esc(r.payload.entry_scenario)}；成本 ${fee(r.cost)}。</p><p>声明数据截止：${esc(r.cutoff)}；本地入库：${dt(r.recorded_at)}。历史来源的声明时间不等于不可变事前冻结证据。</p><p>最近收盘 ${esc(m.close)} · 20日乖离 ${esc(m.bias20_pct??(m.bias20==null?null:m.bias20*100))}% · ATR14 ${esc(m.atr14)} · 量/前5日 ${esc(m.volume_vs_prior5??m.volume_ratio5)}。</p><p>研究依据：${esc(r.payload.reason||'见历史报告')}</p><p>赔率与限制：${esc(r.payload.payoff_assumption||'尚未建立收益分布')}</p><h3>入场与费用敏感性（保本退出价）</h3><pre>${esc(JSON.stringify(r.payload.cost_sensitivity||r.payload.sensitivity||[],null,2))}</pre><h3>均线与五日斜率</h3><pre>${esc(JSON.stringify({MA:m.ma,斜率百分比:m.ma_slope_5d_pct,收益百分比:m.returns_pct||m.returns},null,2))}</pre><p>缺失：${esc((r.payload.missing||[]).join('、')||'请查原始数据证据')}</p><p>模型：${esc(r.model)}；来源：${esc(r.payload.source||'事前输入文件')}。</p>`;$('closeDetail').onclick=()=>$('details').hidden=true;$('details').scrollIntoView({behavior:'smooth',block:'nearest'});}
function renderEval(){const e=S.evaluations.find(x=>x.model===$('model').value&&x.basis===$('basis').value);$('evalMetrics').innerHTML=kpi('可评价样本',e?.n??0,'不包含未成交、缺失与事后预测')+kpi('独立信号日',e?.days??0,'同日多股不能视为独立实验')+kpi('Brier 概率误差',e?.brier==null?'未验证':e.brier.toFixed(4),'越低越好，需与基线比较')+kpi('平均扣费收益',pc(e?.mean_net_return),'非资金净值');$('calibration').innerHTML=e?.n?e.bins.map(b=>`<div class="calrow">${b.lo}–${b.lo+10}% 桶 · n=${b.n}<br>预测 ${pc(b.predicted)} / 实际 ${pc(b.observed)}</div>`).join(''):empty('暂无合格事前结算样本，不能给出校准结论');$('sensitivity').innerHTML=e?.n?e.cost_sensitivity.map(x=>`<div class="flowrow"><b>成本 ${fee(x.cost)}</b><span>平均净收益 ${pc(x.mean_return)} / 盈利比例 ${pc(x.win_rate)}</span></div>`).join(''):empty('0.20% / 0.45% / 0.80%：等待同规则结果');}
async function load(){try{$('refresh').disabled=true;const r=await fetch('/api/state');if(!r.ok)throw Error('读取失败 '+r.status);S=await r.json();const prev=$('day').value;$('day').innerHTML=S.days.map(x=>`<option value="${esc(x)}">${esc(x.replace(/(....)(..)(..)/,'$1-$2-$3'))}${x===S.days[0]?' · 最新':''}</option>`).join('');if(S.days.includes(prev))$('day').value=prev;$('error').hidden=true;versions();render()}catch(e){$('error').hidden=false;$('error').textContent='本地数据读取失败：'+e.message}finally{$('refresh').disabled=false}}
$('day').onchange=()=>{quoteSelectedDay=$('day').value;versions();render()};$('predictionVersion').onchange=render;$('search').oninput=renderRows;$('basis').onchange=renderEval;$('model').onchange=renderEval;$('refresh').onclick=load;$('print').onclick=()=>window.print();$('rows').onclick=e=>{const b=e.target.closest('button[data-id]');if(b)details(Number(b.dataset.id))};load();

function renderContext(){const c=S.research_context||{observations:[],tasks:[]};$('contextAudit').innerHTML='<p>审查截止：'+esc(c.cutoff||'未登记')+'</p>'+c.observations.map(r=>'<div class="notice"><b>'+esc(r.instrument+' '+(r.name||''))+'</b> · '+(r.eligible?'字段校验通过，预测价值待验证':'隔离 / 待核验')+'<p>'+esc((r.exclusions||[]).join('；'))+'</p><small>'+esc(r.source)+'</small></div>').join('');$('researchTasks').innerHTML=c.tasks.map(t=>'<details><summary>'+esc(t.priority+' · '+t.name)+' · '+t.eligible_n+'/'+t.observed_n+'条观察可用</summary><p>研究问题：'+esc(t.hypothesis)+'</p><p>下一步：'+esc(t.next_action)+'</p></details>').join('');}

const originalContextRenderer=renderContext;
renderContext=function(){originalContextRenderer();const r=S.research_context?.research_review;if(!r)return;const holder=document.createElement('div');holder.className='tablewrap';holder.innerHTML='<h3>增量证据审查 · D '+esc(r.signal_date)+'</h3><p>'+esc(r.decision)+'。本区独立于上方预测版本，未回写旧预测。</p><table><thead><tr><th>股票</th><th>开盘→10:00 / 收盘</th><th>行业5日 / 20日</th><th>反证与风险</th></tr></thead><tbody>'+r.cases.map(c=>'<tr><td>'+esc(c.name)+'<small>'+esc(c.code)+'</small></td><td>'+c.minute.open_to_1000_pct.toFixed(2)+'% / '+c.minute.open_to_close_pct.toFixed(2)+'%</td><td>'+c.sector_returns_pct['5'].toFixed(2)+'% / '+c.sector_returns_pct['20'].toFixed(2)+'%</td><td>'+esc(c.rebuttal)+'</td></tr>').join('')+'</tbody></table><p>缺口：'+esc(r.blockers.join('；'))+'</p>';const a=r.active_followthrough;if(a){const panel=document.createElement('div');panel.className='notice';panel.innerHTML='<h3>主动执行进度 · '+esc(a.recorded_at)+'</h3><p>历史分钟含10:00记录 '+a.history.minute_with1000+' 份；探索性竞价→次日10:00价格对 '+a.pairs.price_pairs+' 组 / '+a.pairs.unique_entry_days+' 个入场日。合格校准样本仍为 0。</p><p>结果取证任务 '+a.capture_jobs+' 项；本次到期 '+a.capture_due_now+' 项。未写入未来结算。</p><p>网页12股观察组：开盘至收盘上涨 '+a.cohort.positive_from_open+' 只，跌超5% '+a.cohort.loss5_from_open+' 只。与终端13成分不一致，未用作正式指数广度。</p><p>资金：'+esc(a.funding_status)+'。历史材料属于补充数据源，未改变原预测概率。</p>';holder.prepend(panel);}$('contextAudit').prepend(holder);};

const contextBeforeWeights=renderContext;
renderContext=function(){contextBeforeWeights();const a=S.research_context?.research_review?.catalyst_weights;if(!a)return;const box=document.createElement('div');box.className='notice';box.innerHTML='<h3>历史标签采集与初始权重 · D '+esc(a.reasons.signal_date)+'</h3><p>版本 '+esc(a.policy.version)+' · 初始研究假设，尚未校准。涨停原因标签覆盖 '+a.reasons.reason_observed_candidates+'/'+a.reasons.expected_candidates+'，原始消息已核验 '+a.reasons.reason_verified_candidates+'；不回写旧概率。</p><div class="tablewrap"><table><thead><tr><th>研究维度</th><th>初始权重</th><th>证据要求</th></tr></thead><tbody>'+Object.entries(a.policy.weights).map(([k,v])=>'<tr><td>'+esc(a.policy.dimensions[k].name)+'</td><td>'+Math.round(v*100)+'%</td><td>'+esc(a.policy.dimensions[k].rule)+'</td></tr>').join('')+'</tbody></table></div><p>实际结果可训练样本 '+a.challenge.n+'，独立日期 '+a.challenge.days+'。权重候选生成：'+(a.challenge.state==='BLOCKED_INSUFFICIENT_ELIGIBLE_RESULTS'?'等待合格结果':'仅影子候选')+'。研究分不是盈利概率；缺失项不重分权重；执行受限单列。</p>'+a.reasons.observations.map(r=>'<details><summary>'+esc(r.name+' '+r.code)+(r.in_current_pool?' · 当期候选':' · 池外参考')+'</summary><p>'+esc(r.raw_reason)+'</p><p>同花顺标签；原始发布时间及公告待核验，未给予催化分。</p>'+(r.vendor_cited_sources?'<p>详情引用：'+esc(r.vendor_cited_sources.join('；'))+'</p>':'')+(r.detail_review?'<p>时效与反证：'+esc(r.detail_review)+'</p>':'')+'</details>').join('');$('contextAudit').prepend(box);};

function renderClosedLoop(){const c=S.closed_loop;if(!c)return;const r=c.last_run;const box=document.createElement('div');box.className='notice';box.innerHTML='<h3>预测与结果闭环 · 实际运行状态</h3><p>事前预测 '+c.prospective+' 条；完整契约绑定 '+c.contract_bound+' 条；六维证据齐全 '+c.complete_features+' 条；已录入结果 '+c.outcomes+' 条。</p><p>新预测已强制全池、交易日历、证据哈希、六维特征及权重版本检查。旧预测不回填，缺失不记零。</p><p>最近维护：'+esc(r?.state||'尚未运行')+' · '+dt(r?.at)+'；备份回读 '+esc(r?.backup?.status||'未验证')+'；结果取证任务 '+(r?.capture_jobs?.length??0)+'，失败 '+(r?.failures??0)+'。</p><p>新学习模块已实现收益回归及独立概率校准；当前是否可训练见学习底座状态，自动晋升禁用。维护入口由既有夜间任务调用，电脑重启后的无人值守运行尚未验证。</p>';$('alerts').prepend(box);}

const contextBeforeBoundReview=renderContext;
renderContext=function(){
 contextBeforeBoundReview();
 const rows=dayRows().filter(r=>r.payload.research_contract==='RESEARCH_FREEZE_V1');
 if(!rows.length)return;
 const names={market:'市场情绪',theme:'题材资金',price_volume:'量价',limit_quality:'封板',catalyst:'催化',payoff:'赔率'};
 const box=document.createElement('div');box.className='notice';
 box.innerHTML='<h3>当前预测版本 · 证据与权重贡献</h3><p>'+esc(rows[0].model)+' · 截止 '+dt(rows[0].cutoff)+'</p><p>以下来自当前选中的冻结记录。覆盖率指有证据评分的权重占比，不是全量数据完整率。缺失不重分权重；综合评分不可用，贡献值不是盈利概率。下方标签采集板块为此前历史快照。</p>'+rows.map(r=>{const p=r.payload,w=p.weighted_review;return '<details><summary>'+esc(r.name)+(rated(r)?' · 盈利 '+pc(r.p):' · 无信息占位，不评级')+' · 权重覆盖 '+pc(w.coverage_weight)+'</summary><p>'+esc(p.reason)+'</p><p>反证：'+esc(p.counterevidence)+'</p><table><thead><tr><th>维度</th><th>方向分 × 权重 → 贡献</th><th>证据 / 缺失</th></tr></thead><tbody>'+Object.entries(p.weighted_features).map(([k,f])=>{const v=w.contributions[k];return '<tr><td>'+esc(names[k])+'</td><td>'+(v?esc(v.score+' × '+pc(v.weight)+' → '+v.contribution.toFixed(3)):'缺失')+'</td><td>'+esc(f.rationale||f.missing_reason)+'</td></tr>';}).join('')+'</tbody></table><p>失效条件：'+esc(p.invalidation)+'</p><p>执行风险：'+esc(p.execution_risk)+'</p></details>';}).join('');
 $('contextAudit').prepend(box);
};

const priorClosedLoop=renderClosedLoop;
renderClosedLoop=function(){priorClosedLoop();const l=S.learning;if(!l)return;const b=document.createElement('div');b.className='notice';b.innerHTML='<h3>跨交易日学习底座</h3><p>'+esc(l.objective)+'</p><p>方法 '+esc(l.method)+'；归档 '+(l.snapshots??0)+' 个快照 / '+(l.days??0)+' 个D日；结果标签 '+(l.settled??0)+'。</p><p>最近全池采集：'+esc(l.last_run?.state||'未执行')+' · 有效 '+(l.last_run?.valid??0)+' / '+(l.last_run?.expected??0)+'</p><p>训练：'+esc(l.last_model?.state||'尚未执行')+'；合格日期 '+(l.last_model?.eligible_days??0)+'，样本 '+(l.last_model?.eligible_rows??0)+'</p><p>收益回归 + 盈利分类 + 独立校准；按日期滚动验证。当前仅数值基线14项，资金、封板、催化仍须补齐；代理与实际分库口径评价，不合并业绩。</p>';$('alerts').prepend(b);};

const beforeEvidencePanel=renderClosedLoop;
renderClosedLoop=function(){beforeEvidencePanel();const l=S.learning,e=l?.enrichment;if(!e)return;const b=document.createElement('div');b.className='notice';b.innerHTML='<h3>每日多维证据 · D '+esc(e.day)+'</h3><p>涨停原因 '+e.reason_count+'/'+e.candidates+'；个股20日资金 '+e.flow_count+'/'+e.candidates+'；行业资金 '+e.industry_days+' 日；概念资金 '+(e.concept_days??0)+' 日；情绪指数指标 '+Object.keys(e.index_metrics).length+' 项。</p><p>历史隔离批次 '+l.history_quarantined+'；消融实验记录 '+l.experiment_runs+'（不等于已训练模型）。结果队列：'+esc(JSON.stringify(l.result_queue))+'</p><p>以下是供应商标签，原始公告未核验；不会直接调整概率。资金成分映射、Level2和封单金额口径仍单列缺口。</p>'+e.rows.map(r=>'<details><summary>'+esc(r.code)+' · '+esc(r.limit_reason||'原因缺失')+'</summary><p>缺失：'+esc(r.missing.join('、'))+'</p></details>').join('');$('alerts').prepend(b);};

const beforePrimaryReviewPanel=renderClosedLoop;
renderClosedLoop=function(){beforePrimaryReviewPanel();const l=S.learning,m=l?.membership,q=l?.primary_news_queue,r=l?.readiness;if(!m&&!q&&!r)return;const b=document.createElement('div');b.className='notice';b.innerHTML='<h3>原始公告与板块对应 · 新增证据</h3><p>以下独立于历史冻结预测；原公告仅部分核实，未确认当日涨停因果及全部消息时间。</p>'+(m?'<p>D '+esc(m.day)+' · 当前成分观察 '+dt(m.observed_at)+'。已关联 '+m.rows.filter(x=>x.linked_sectors.length).length+'/'+m.rows.length+'只；历史成分有效期未知，不能倒填D日，不自动改概率。</p>'+m.rows.map(x=>'<details><summary>'+esc(x.code)+' '+esc(x.name)+' · '+x.linked_sectors.length+'个资金板块</summary><p>'+esc(x.linked_sectors.map(y=>y.name).join('、'))+'</p></details>').join(''):'')+(q?'<p>逐股原文审查及剩余缺口：</p>'+q.rows.map(x=>'<details><summary>'+esc(x.code)+' · '+(x.review_id?'部分原文已核实':'待原文核验')+'</summary><p>'+esc(x.remaining.join('；'))+'</p></details>').join(''):'')+(r?'<p>运行检查 '+dt(r.at)+'：下一常规时点 '+dt(r.next_regular_at)+'；数据库 '+esc(r.db_integrity)+'；API已实测。自然无人值守仍待验证。</p>':'');$('alerts').prepend(b);};

const renderBeforeActiveResearch=render;
render=function(){
 renderBeforeActiveResearch();
 const a=S.learning?.active_research;if(!a)return;
 const box=document.createElement('div');box.className='notice';
 box.innerHTML='<h3>Codex 主动研究 · '+esc(a.version)+'</h3><p>待办 '+a.pending.length+' · 假设 '+a.proposals.length+' · 已记录 Agent 会话 '+a.worker_runs.length+'。候选实验与正式采用分开；自动生产晋升关闭。</p>'+a.pending.map(t=>'<details><summary>'+esc(t.topic)+' · '+esc(t.disposition?.state||'OPEN')+'</summary><p>'+esc(t.question)+'</p><p>'+esc(t.disposition?.reason||'等待 Agent 读取证据并处理')+'</p></details>').join('')+'<p>任务生成不代表研究完成；当前样本、实验阻断和自然执行须分别核验。</p>';
 $('alerts').prepend(box);
};

// Cross-date ledger uses first prospective record per D/code; versions remain inspectable.
function historyRows(){const m=new Map();for(const r of [...S.predictions].sort((a,b)=>a.id-b.id)){const k=r.signal_date+'|'+r.code,old=m.get(k);if(!old||(old.provenance!=='PROSPECTIVE_LOCAL'&&r.provenance==='PROSPECTIVE_LOCAL'))m.set(k,r)}return [...m.values()]}
function renderHistory(){
 const all=historyRows(),forward=all.filter(r=>r.provenance==='PROSPECTIVE_LOCAL'),due=forward.filter(r=>r.research_stage==='DUE_FOR_OUTCOME_EVIDENCE'),settled=forward.filter(r=>displayOutcomes(r).some(o=>o.status==='SETTLED'));
 $('historyKpis').innerHTML=kpi('累计信号日',new Set(all.map(r=>r.signal_date)).size,'有结构化预测的日期')+kpi('事前 D×股票',forward.length,'每股每日首次事前版本去重')+kpi('已到期 / 已登记结算',due.length+' / '+settled.length,'首次事前版本口径；不是成交数量')+kpi('预测版本记录',S.predictions.length,'保留修改历程，不当作独立样本');
 $('historyRows').innerHTML=S.days.map(day=>{const rs=all.filter(r=>r.signal_date===day),p=rs.filter(r=>r.provenance==='PROSPECTIVE_LOCAL'),v=S.predictions.filter(r=>r.signal_date===day),f=S.official[day];return `<tr><td><button data-day="${esc(day)}">${esc(day)}</button></td><td>${rs.length} / ${p.length}</td><td>${new Set(v.map(r=>r.model)).size} / ${v.length}</td><td>${p.filter(r=>r.research_stage==='DUE_FOR_OUTCOME_EVIDENCE').length}</td><td>${p.filter(r=>displayOutcomes(r).some(o=>o.basis==='QUOTE_PROXY'&&o.status==='SETTLED')).length} / ${p.filter(r=>displayOutcomes(r).some(o=>o.basis==='ACTUAL'&&o.status==='SETTLED')).length}<small>旧情景排除 ${p.filter(r=>displayOutcomes(r).some(o=>o.basis==='QUOTE_PROXY'&&o.status==='OUT_OF_SCENARIO')).length}</small></td><td>${esc(f?.rows.filter(x=>x.candidate_rank<=2).map(x=>x.name).join(' / ')||'正式身份待核验')}</td></tr>`}).join('');
 $('historyRows').onclick=e=>{const b=e.target.closest('[data-day]');if(b){selectSignalDay(b.dataset.day);$('candidates').scrollIntoView({behavior:'smooth'})}};
 const queue=S.learning?.result_queue||{},names={MISSING_BROKER_EVIDENCE:'缺真实成交凭据',NEEDS_EXECUTION_REVIEW:'行情代理待执行性审核',WAIT_EXIT:'待退出时点',OUT_OF_SCENARIO:'入场价格超出情景'};
 $('outcomeProgress').innerHTML='<p>结果采集队列（最新维护快照，任务数不等于独立股票数）：'+Object.entries(queue).map(([k,v])=>esc(names[k]||k)+' '+esc(v)).join('；')+'</p><p>真实成交缺凭据不会阻止单独审核行情代理。价格采集、可执行性审核、合格结算是三个阶段；不将待审记录计为收益。</p>'+(settled.length?'':'<div class="notice">目前没有可展示的首次事前版本已结算记录；无法计算可靠的官方 / 本地收益差、校准曲线或排序进步。原始数据归档数量不等于学习样本。</div>');
 const filter=$('ledgerDay').value,lr=all.filter(r=>!filter||r.signal_date===filter);
 $('ledgerRows').innerHTML=lr.map(r=>`<tr><td>${esc(r.signal_date)}</td><td>${esc(r.name)}<small>${esc(r.code)}</small></td><td>${rated(r)?pc(r.p):'无信息占位'}<small>${esc(prov(r.provenance))}</small></td><td>${dt(r.entry_at)}<small>→ ${dt(r.exit_at)}</small></td><td>${displayOutcomes(r).length?displayOutcomes(r).map(o=>esc((o.basis==='ACTUAL'?'真实':'代理')+' · '+stat(o.status))+'<small>入 '+esc(o.entry_price)+' / 出 '+esc(o.exit_price)+'</small>'+(o.status==='SETTLED'&&o.entry_price>0&&o.exit_price!=null?'<small>扣费 '+pc(o.exit_price/o.entry_price-1-r.cost)+'</small>':'')).join(''):'未登记结果'}</td><td>${esc(r.model)}<small>ID ${r.id}</small></td></tr>`).join('');
}
const renderBeforeHistory=render;
render=function(){renderBeforeHistory();const prev=$('ledgerDay').value;$('ledgerDay').innerHTML='<option value="">全部日期</option>'+S.days.map(d=>`<option value="${esc(d)}">${esc(d)}</option>`).join('');$('ledgerDay').value=prev;renderHistory();
 // Keep historical evidence available but remove it from current-day headline flow.
 const audit=$('contextAudit'),fold=document.createElement('details'),title=document.createElement('summary');title.textContent='历史补充证据与采集记录（展开查看各项原始日期）';fold.append(title);for(const child of [...audit.children]){if(child.textContent.includes('当前预测版本'))continue;fold.append(child)}audit.append(fold);
};
$('ledgerDay').onchange=renderHistory;

const reasonText=x=>({NO_SAME_POOL_PRE_CUTOFF_SNAPSHOT:'缺同池且早于预测截止的特征快照',POOL_OR_SNAPSHOT_EVIDENCE_UNVERIFIED:'名单/快照证据尚未核验',NOT_PROSPECTIVE:'历史记录，不作前瞻验证',INCOMPLETE_FEATURE_COHORT:'全池特征不完整，训练暂不准入',NO_COMPLETE_PROSPECTIVE_SNAPSHOT:'缺完整事前特征快照',MISSING_LABEL:'结果标签未齐',OUT_OF_SCENARIO:'超出入场情景，不能计为亏损或零收益',MISSING:'仍缺结果证据',UNEXITED:'未退出，敞口未解决',SETTLED:'已审核结算',UNFILLED:'未买入',WAIT_ENTRY:'待入场日',WAIT_EXIT:'待退出日',MISSING_QUOTES:'待补报价证据',MISSING_BROKER_EVIDENCE:'缺真实成交凭据',NEEDS_EXECUTION_REVIEW:'不限跳空，待成交可执行性审核',CONFLICT:'两套结果冲突，暂停使用'}[x]||x);
function renderReview(){
 const v=S.reconciliation;if(!v)return;const basis=$('reviewBasis').value,ids=new Set(dayRows().map(r=>r.id)),rs=v.rows.filter(r=>ids.has(r.prediction_id));
 $('lineageSummary').innerHTML='<div class="notice subdued">特征时点与全池身份可关联 '+v.linked_predictions+' / '+v.rows.length+' 条预测版本记录；关联不等于训练准入。审核刷新 '+dt(v.at)+'。</div>';
 $('lineageRows').innerHTML='<table><thead><tr><th>股票 / 预测ID</th><th>当时概率</th><th>特征快照</th><th>结果状态 / 扣费收益</th><th>尚缺什么</th></tr></thead><tbody>'+rs.map(r=>{const o=r.outcomes[basis];return '<tr><td>'+esc(r.name)+'<small>'+esc(r.code)+' · #'+r.prediction_id+'</small></td><td>'+(r.rank_eligible?pc(r.p):'无信息占位')+'</td><td>'+esc(r.snapshot_id??'未关联')+'<small>'+esc(r.member_state==='VALID_NUMERIC_BASELINE'?'数值特征齐全':r.member_state==='MISSING'?'个股特征缺失':r.member_state)+'</small></td><td>'+esc(reasonText(o.status))+' / '+pc(o.net)+'<small>'+esc(({NONE:'尚未登记',LEARNING_LABEL:'学习结果记录',PREDICTION_OUTCOME:'预测结果记录'})[o.source]||o.source)+(o.id?' #'+o.id:'')+'</small>'+(o.snapshot_id?'<small>结果所属快照 #'+o.snapshot_id+'</small>':'')+'</td><td>'+esc(r.blockers.map(reasonText).join('；')||'特征关联通过；训练另审全池结果')+'</td></tr>'}).join('')+'</tbody></table>';
 const comparisons=v.comparisons.filter(x=>x.model===$('predictionVersion').value&&x.day===$('day').value&&x.basis===basis);
 $('matchedReview').innerHTML=comparisons.length?comparisons.map(x=>{if(!x.evaluation?.length)return empty('尚不能比较：'+x.reason);return x.evaluation.map(d=>'<p>D '+esc(d.day)+' · 全池 '+d.pool+'；已结算 '+d.settled+'；未买入 '+d.unfilled+'。以下为条件收益，不是资金净值。</p><table><thead><tr><th>往返成本</th><th>本地前二</th><th>正式前二</th><th>全池</th></tr></thead><tbody>'+d.costs.map(z=>'<tr><td>'+fee(z.cost)+'</td>'+['independent_top2','official_top2','equal_pool'].map(k=>'<td>'+pc(z.selections[k]?.conditional_mean_net)+'<small>成交权重 '+(z.selections[k]?.filled_weight??0).toFixed(2)+' / '+(z.selections[k]?.selected_weight??0).toFixed(2)+'；最差 '+pc(z.selections[k]?.worst_filled_net)+'</small></td>').join('')+'</tr>').join('')+'</tbody></table>').join('')}).join(''):empty('当前版本缺少预先登记的同口径对照契约，保留归档，不追认验证。');
 const ds=v.datasets[basis];$('trainingGaps').innerHTML='<p>训练准入：'+ds.rows+' 行 / '+ds.days+' 个日期。'+esc(ds.error||'')+'</p>'+ds.excluded.map(x=>'<div class="flowrow"><b>D '+esc(x.day)+'</b><span>'+esc(reasonText(x.reason))+'</span></div>').join('');
 $('reviewQueue').innerHTML='<table><thead><tr><th>D / 股票</th><th>取证状态</th><th>特征缺口</th><th>既有标签</th></tr></thead><tbody>'+v.queue.items.filter(x=>x.basis===basis).map(x=>'<tr><td>'+esc(x.day)+' / '+esc(x.code)+'<small>'+esc(prov(x.provenance))+'</small></td><td>'+esc(reasonText(x.state))+'</td><td>'+esc(x.feature_blocker||x.member_state)+'</td><td>'+esc(x.previous_status?reasonText(x.previous_status):'未登记')+'</td></tr>').join('')+'</tbody></table>';
 const a=S.learning?.active_research;
 $('researchTimeline').innerHTML=a?'<p>已登记 '+a.proposals.length+' 个假设；显示最近 '+a.runs.length+' 次实验、'+a.worker_runs.length+' 次研究会话。数量不代表方法有效。</p>'+a.proposals.map(p=>'<div class="notice subdued"><b>假设 #'+p.id+'</b><p>'+esc(p.hypothesis)+'</p><p>可证伪条件：'+esc(p.falsification)+'</p><small>登记 '+dt(p._recorded_at)+'</small></div>').join('')+a.runs.map(r=>'<div class="flowrow"><b>实验 #'+r.id+'</b><span>'+esc(r.state||r.result?.state||'见证据记录')+' · '+dt(r._recorded_at)+'</span></div>').join('')+(a.history_events||[]).map(e=>'<div class="flowrow"><b>处置 '+esc(e.state)+'</b><span>'+esc(e.reason)+'</span></div>').join('')+a.pending.map(t=>'<div class="flowrow"><b>'+esc(t.topic)+'</b><span>'+esc(t.disposition?.reason||t.question)+'</span></div>').join(''):empty('尚无研究记录');
}
const beforeReview=render;render=function(){beforeReview();renderReview()};$('reviewBasis').onchange=renderReview;

function renderEffectiveness(){
 const v=S.effectiveness;if(!v){$('effectivenessKpis').innerHTML=empty('尚未生成本地预测核验报告');return;}
 const q=v.quote_ledger,z=q.summary;
 $('effectivenessTime').textContent='核验 '+dt(v.as_of);
 $('effectivenessKpis').innerHTML=kpi('已到期 / 本地样本',z.due+' / '+z.local_unique,'按股票与D去重，不重复预测版本')+kpi('已核验报价结果',z.verified,'有入场、10:00、复权及日线交叉证据')+kpi('执行代理 / 真实结算',z.execution_settled+' / '+z.actual_settled,'报价核验不计入这两个数')+kpi('尚未到期',z.waiting,'等待各自T+1退出日');
 renderQuoteDay();
 $('quoteComparison').innerHTML='<p>沿用当时冻结概率排序选前二，并列分摊名额；以下含无法确认成交的报价，仅供排序探索。逐日等权，不是账户净值。</p>'+v.comparison.days.map(d=>'<h4>D '+esc(d.day)+' · '+d.pool+'只</h4><table><thead><tr><th>成本</th><th>本地前二</th><th>全池</th><th>官方前二</th><th>本地−全池（百分点）</th></tr></thead><tbody>'+d.costs.map(x=>{const sel=x.selections,a=sel.independent_top2?.conditional_mean_net,b=sel.equal_pool?.conditional_mean_net;return '<tr><td>'+fee(x.cost)+'</td><td>'+fee(a)+'</td><td>'+fee(b)+'</td><td>'+fee(sel.official_top2?.conditional_mean_net)+'</td><td>'+(a==null||b==null?'—':((a-b)*100).toFixed(2))+'</td></tr>'}).join('')+'</tbody></table>').join('')+'<p>官方名次缺失只暂停官方对照。报价层不校准可执行盈利概率；两个交易日不足以证明预测有效。</p>';
 const e=v.experiment;
 $('quoteExperiment').innerHTML=e?'<p>候选：按冻结20日乖离较低者选前二；对照原冻结概率榜前二。结果为事后探索，未采用新方法。</p><pre style="white-space:pre-wrap">'+esc(e.summary_text||e.conclusion||e.decision||'详见归档实验报告')+'</pre>':empty('实验结果待归档');
}
const beforeEffectiveness=render;render=function(){beforeEffectiveness();renderEffectiveness()};

let quoteSelectedDay=null;
function quoteDays(){return [...new Set((S?.effectiveness?.quote_ledger.rows||[]).map(r=>r.day))].sort();}
function quoteReturn(value){
 if(value==null||!Number.isFinite(value))return '<span class="quote-return flat">—</span>';
 const n=Math.round(Math.abs(value)*10000)/100,dir=n===0?'flat':value>0?'up':'down';
 return '<strong class="quote-return '+dir+'">'+(dir==='up'?'↑ +':dir==='down'?'↓ −':'')+n.toFixed(2)+'%</strong>';
}
function renderQuoteDay(){
 const days=quoteDays();
 if(quoteSelectedDay==null)quoteSelectedDay=$('day').value||days.at(-1)||null;
 const i=days.indexOf(quoteSelectedDay),eligible=r=>r.rank_eligible!==false&&r.p!=null;
 const rows=(S?.effectiveness?.quote_ledger.rows||[]).filter(r=>r.day===quoteSelectedDay).sort((a,b)=>(eligible(b)?b.p:-1)-(eligible(a)?a.p:-1)||a.code.localeCompare(b.code));
 const f=S?.official?.[quoteSelectedDay];
 const dateLabel=x=>x?new Date(x).toLocaleDateString('zh-CN',{timeZone:'Asia/Shanghai'}):'待核验';
 $('quoteTiming').textContent=rows.length?'T '+dateLabel(rows[0].entry_at)+' 竞价入场 → T+1 '+dateLabel(rows[0].exit_at)+' 10:00退出':'';
 $('quoteDayHeading').textContent=quoteSelectedDay?'D '+quoteSelectedDay.replace(/(....)(..)(..)/,'$1-$2-$3')+' · '+rows.length+'只':'';
 $('quotePageStatus').textContent=days.length?(i+1)+' / '+days.length+' 个日期':'暂无预测日期';
 $('quotePrev').disabled=i<=0;$('quoteNext').disabled=i<0||i>=days.length-1;
 const risks={ENTRY_AT_UP_LIMIT_QUEUE_UNKNOWN:'竞价涨停，排队未知',EXIT_AT_DOWN_LIMIT_QUEUE_UNKNOWN:'退出跌停，排队未知',ORDER_QUANTITY_QUEUE_AND_1000_FILL_NOT_VERIFIED:'订单规模与精确成交未验证'};
 $('quoteLedger').innerHTML=rows.length?'<table><thead><tr><th>本地名次</th><th>股票</th><th>DC20身份</th><th>盈利概率<small>冻结 · 未校准</small></th><th>竞价 → 10:00</th><th>扣费报价收益<small>往返成本0.45%</small></th><th>状态 / 条件与风险</th></tr></thead><tbody>'+rows.map(r=>{
  const rank=eligible(r)?1+rows.filter(x=>eligible(x)&&x.p>r.p).length:'未评级',same=rows.filter(x=>eligible(x)&&x.p===r.p).length;
  const profit=f?.rows.find(x=>x.ts_code===r.code)?.candidate_rank,promotion=f?.promotion.find(x=>x.ts_code===r.code)?.promotion_rank;
  const a=profit>=1&&profit<=2,b=promotion>=1&&promotion<=3,tags=[];
  if(a)tags.push('盈'+profit);if(b)tags.push('晋'+promotion);
  const identity=tags.length?'<span class="rank-tag '+(a&&b?'overlap':a?'profit':'promotion')+'">'+tags.join(' · ')+'</span>':f?'—':'身份待核验';
  const waiting=['WAIT_ENTRY','WAIT_EXIT'].includes(r.quote_status),state=r.quote_status==='WAIT_ENTRY'?'待入场':r.quote_status==='WAIT_EXIT'?'待退出':r.quote_status==='VERIFIED_PRICE_PAIR'?'报价已核验':'待补数据';
  return '<tr><td>'+rank+(eligible(r)&&same>1?'（并列）':'')+'</td><td><b>'+esc(r.name)+'</b><small>'+esc(r.code)+'</small></td><td>'+identity+'</td><td>'+pc(r.p)+(eligible(r)?'':'<small>无信息占位</small>')+'</td><td>'+esc(r.entry_price)+' → '+esc(r.exit_price)+'</td><td>'+quoteReturn(waiting?null:r.net_return)+'</td><td><span class="quote-state">'+state+'</span>'+(waiting?'': '<small>'+esc(r.original_scenario_applicable===true?'原条件内':r.original_scenario_applicable===false?'原条件外 · 收益复盘':'旧条件未知')+'</small>')+'<small>'+esc((r.execution_risks||[]).filter(x=>x!=='ORDER_QUANTITY_QUEUE_AND_1000_FILL_NOT_VERIFIED').map(x=>risks[x]||x).join('；'))+'</small></td></tr>';
 }).join('')+'</tbody></table>':empty('暂无逐股预测记录');
}
function moveQuoteDay(step){const days=quoteDays(),i=days.indexOf(quoteSelectedDay),j=i+step;if(j>=0&&j<days.length){selectSignalDay(days[j]);}}
$('quotePrev').onclick=()=>moveQuoteDay(-1);$('quoteNext').onclick=()=>moveQuoteDay(1);

function selectSignalDay(day){if(!S?.days.includes(day))return;$('day').value=day;quoteSelectedDay=day;versions();render();}
function moveSignalDay(step){const ds=[...S.days].sort(),i=ds.indexOf($('day').value);if(ds[i+step])selectSignalDay(ds[i+step]);}
function renderDateControl(){const ds=[...S.days].sort(),i=ds.indexOf($('day').value);$('dayPrev').disabled=i<=0;$('dayNext').disabled=i<0||i===ds.length-1;$('dayLatest').disabled=$('day').value===ds.at(-1);}
$('dayPrev').onclick=()=>moveSignalDay(-1);$('dayNext').onclick=()=>moveSignalDay(1);$('dayLatest').onclick=()=>selectSignalDay([...S.days].sort().at(-1));
const beforeDateControl=render;render=function(){beforeDateControl();renderDateControl()};

// Saved evidence readiness, separate from execution settlements and old probabilities.
const beforeLearningProgress=renderClosedLoop;
renderClosedLoop=function(){beforeLearningProgress();renderLearningProgress();};
function renderLearningProgress(){
 const box=$('learningProgress');if(!box)return;
 const q=S.learning?.quote_learning,t=S.learning?.active_research?.tracking;
 if(!q?.summary){box.innerHTML='<p>报价学习尚未完成证据检查；不会将报价条数直接视为可训练样本。</p>';return;}
 const s=q.summary, reasonNames={FUTURE_RESULT:'尚未到退出时间',MISSING_FULL_CANDIDATE_POOL:'缺原冻结完整候选池',NO_PRE_CUTOFF_NUMERIC_SNAPSHOT:'缺原截止前完整数值特征',POST_CUTOFF_SNAPSHOT:'特征归档晚于原截止',INCOMPLETE_OR_INCONSISTENT_ORIGINAL_COHORT:'原池分母未齐',MISSING_QUOTE_LEDGER:'缺已核验报价记录'};
 const reason=x=>reasonNames[x]||x;
 const phase={COMPLETED_AGENT:'研究处置完成',COMPLETED_MAINTENANCE:'维护完成',AWAITING_AGENT:'待 Codex 调查',AGENT_STARTED:'调查中 / 可恢复',FAILED:'失败待重试',INTERRUPTED:'中断待恢复',STARTED:'维护中',RESUMED:'恢复维护中'};
 const origin={ENGINEERING_ACCEPTANCE:'人工工程验收',SCHEDULED:'定时触发记录',MANUAL:'人工执行'};
 box.innerHTML='<div class="learning-metrics">'+[['原事前预测',s.original_predictions],['报价核验',s.verified_quote_rows],['原截止前特征',s.complete_feature_rows],['合格学习样本',s.eligible_rows+' 条 / '+s.eligible_days+' 日']].map(x=>'<div><span>'+esc(x[0])+'</span><strong>'+esc(x[1])+'</strong></div>').join('')+'</div>'+
 '<p>训练门槛：至少 300 条，训练 / 校准 / 测试 60 / 20 / 20 日；跨边界持有期及晚到标签还会整日剔除。当前 '+esc(({BLOCKED_INSUFFICIENT_DATA:'样本不足，尚未训练',WAITING_NEW_DATA_OR_WEEKLY_BUDGET:'等待新增完整日期及每周训练窗口',TRAINED_RESEARCH_ONLY:'已完成研究训练，等待新的前瞻验证'})[q.training?.state]||q.training?.state||'未运行')+'。门槛是研究准入条件，不保证有效。</p>'+
 '<div class="tablewrap"><table class="compact-table"><thead><tr><th>D</th><th>原预测 / 完整池</th><th>报价核验</th><th>事前特征</th><th>可学习</th><th>未纳入原因</th></tr></thead><tbody>'+q.days.map(d=>'<tr><td>'+esc(d.day)+'</td><td>'+esc(d.original_predictions)+' / '+esc(d.expected_count??'待核验')+'</td><td>'+d.verified_quote_rows+'</td><td>'+d.complete_feature_rows+'</td><td>'+d.eligible_rows+'</td><td>'+esc(d.reasons.map(reason).join('；')||'完整日期已纳入')+'</td></tr>').join('')+'</tbody></table></div>'+
 '<p class="muted">QUOTE_RETURN 只研究报价收益；不计入真实结算，不校准旧条件概率。缺失原事前证据不以后补行情倒填。</p>'+
 '<div class="sectionhead"><h3>Codex 研究执行证据</h3><span>工程验收 '+(t?.engineering_completed??0)+' 次 · 定时关联完成 '+(t?.scheduled_linked_completed??0)+' 次</span></div>'+
 ((t?.runs?.length)?'<div class="research-run-list">'+t.runs.slice(0,3).map(r=>'<div><b>'+esc(phase[r.phase]||r.phase)+'</b> · '+esc(origin[r.origin]||r.origin)+' · '+dt(r.at)+'<small>运行 '+esc(r.run_id)+' · 尝试 '+r.attempt+(r.disposition_ids?.length?' · 处置 '+r.disposition_ids.length+' 项':'')+'</small></div>').join('')+'</div>':'<p>尚无关联触发来源的完整研究记录。</p>')+
 '<p class="muted">维护成功、任务生成、Agent 调查分别留痕。自然无人值守仍须与外部调度记录核对，人工验收不计作定时成功。</p>';
}
